# Generated by Django 6.0.2 on 2026-03-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role_name',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('staff', 'Staff'), ('receptionist', 'Receptionist'), ('viewer', 'Viewer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_name',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('staff', 'Staff'), ('receptionist', 'Receptionist'), ('viewer', 'Viewer')], max_length=50),
        ),
    ]
