# Generated by Django 6.0.2 on 2026-08-13 19:11

import accounts.managers
import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


def create_default_gym(apps, schema_editor):
    Gym = apps.get_model("accounts", "Gym")
    User = apps.get_model("accounts", "User")
    gym, _ = Gym.objects.get_or_create(slug="default", defaults={"name": "Default Gym"})
    User.objects.filter(gym__isnull=True).exclude(role_name="super_admin").update(gym=gym)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_manager_staff_default_write_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gyms',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.managers.UserManager()),
                ('all_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role_name',
            field=models.CharField(choices=[('super_admin', 'Super Administrator'), ('admin', 'Administrator'), ('manager', 'Manager'), ('staff', 'Staff'), ('receptionist', 'Receptionist'), ('viewer', 'Viewer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_name',
            field=models.CharField(choices=[('super_admin', 'Super Administrator'), ('admin', 'Administrator'), ('manager', 'Manager'), ('staff', 'Staff'), ('receptionist', 'Receptionist'), ('viewer', 'Viewer')], max_length=50),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.gym'),
        ),
        migrations.AddField(
            model_name='user',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.gym'),
        ),
        migrations.RunPython(create_default_gym, migrations.RunPython.noop),
    ]
