# Generated by Django 6.0.2 on 2026-08-13 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_gym_alter_user_managers_and_more'),
        ('reports', '0004_expense_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.gym'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.gym'),
        ),
    ]
