# Generated by Django 6.0.2 on 2026-07-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0004_systempreferencesettings_calendar_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymprofilesettings',
            name='login_page_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/login_page/'),
        ),
    ]
