# Generated by Django 6.0.2 on 2026-08-13 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_gym_alter_user_managers_and_more'),
        ('system_settings', '0005_gymprofilesettings_login_page_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.gym'),
        ),
        migrations.AddField(
            model_name='backupschedulesettings',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.gym'),
        ),
        migrations.AddField(
            model_name='billingsettings',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.gym'),
        ),
        migrations.AddField(
            model_name='gymprofilesettings',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.gym'),
        ),
        migrations.AddField(
            model_name='membershipplantemplate',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.gym'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.gym'),
        ),
        migrations.AddField(
            model_name='securitysettings',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.gym'),
        ),
        migrations.AddField(
            model_name='systempreferencesettings',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.gym'),
        ),
    ]
