# Generated by Django 6.0.2 on 2026-08-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_backfill_existing_records_to_default_gym'),
        ('attendance', '0008_attendancepolicy_gym_attendancerecord_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancepolicy',
            name='singleton_key',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
        migrations.AddConstraint(
            model_name='attendancepolicy',
            constraint=models.UniqueConstraint(fields=('gym', 'singleton_key'), name='attendance_policy_gym_singleton'),
        ),
    ]
