# Generated by Django 6.0.2 on 2026-06-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_allow_ad_hoc_member_fee_cycles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberfeepayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('online', 'Online'), ('card', 'Card'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staffsalarypayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('online', 'Online'), ('card', 'Card'), ('other', 'Other')], max_length=20),
        ),
    ]
