# Generated by Django 6.0.2 on 2026-06-13 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_memberfeepayment_payment_method_and_more'),
        ('system_settings', '0003_remove_systempreferencesettings_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberfeeplan',
            name='plan_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_fee_plans', to='system_settings.membershipplantemplate'),
        ),
        migrations.AlterField(
            model_name='memberfeeplan',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
    ]
