# Generated by Django 6.0.2 on 2026-08-13 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_gym_alter_user_managers_and_more'),
        ('payments', '0005_memberfeeplan_plan_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberfeecycle',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.gym'),
        ),
        migrations.AddField(
            model_name='memberfeepayment',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.gym'),
        ),
        migrations.AddField(
            model_name='memberfeeplan',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.gym'),
        ),
        migrations.AddField(
            model_name='staffsalarypayment',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.gym'),
        ),
        migrations.AddField(
            model_name='staffsalaryperiod',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.gym'),
        ),
    ]
