# Generated by Django 6.0.2 on 2026-06-13 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_address'),
        ('system_settings', '0003_remove_systempreferencesettings_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership_plan_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='system_settings.membershipplantemplate'),
        ),
    ]
