# Generated by Codex on 2026-06-13

from django.db import migrations


def backfill_member_plan_templates(apps, schema_editor):
    Member = apps.get_model("members", "Member")
    MemberFeePlan = apps.get_model("payments", "MemberFeePlan")
    MembershipPlanTemplate = apps.get_model("system_settings", "MembershipPlanTemplate")

    templates = list(MembershipPlanTemplate.objects.filter(is_active=True))
    for fee_plan in MemberFeePlan.objects.select_related("member").filter(member__membership_plan_template__isnull=True):
        template = None
        if fee_plan.plan_template_id:
            template = fee_plan.plan_template
        else:
            template = next(
                (
                    item
                    for item in templates
                    if item.duration_type == fee_plan.billing_cycle
                    and item.fee == fee_plan.cycle_fee_amount
                ),
                None,
            )

        if template is None:
            continue

        Member.objects.filter(pk=fee_plan.member_id, membership_plan_template__isnull=True).update(
            membership_plan_template=template
        )
        if fee_plan.plan_template_id is None:
            fee_plan.plan_template = template
            fee_plan.save(update_fields=["plan_template", "updated_at"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0005_member_membership_plan_template"),
        ("payments", "0005_memberfeeplan_plan_template_and_more"),
        ("system_settings", "0003_remove_systempreferencesettings_language"),
    ]

    operations = [
        migrations.RunPython(backfill_member_plan_templates, noop_reverse),
    ]
