# Generated by Codex on 2026-06-13

from django.db import migrations


def assign_default_plan_to_unplanned_members(apps, schema_editor):
    Member = apps.get_model("members", "Member")
    MemberFeePlan = apps.get_model("payments", "MemberFeePlan")
    MembershipPlanTemplate = apps.get_model("system_settings", "MembershipPlanTemplate")

    default_template = (
        MembershipPlanTemplate.objects.filter(name__iexact="Basic", is_active=True)
        .order_by("duration_months", "id")
        .first()
    )
    if default_template is None:
        default_template = MembershipPlanTemplate.objects.filter(is_active=True).order_by("duration_months", "id").first()
    if default_template is None:
        return

    members = Member.objects.filter(membership_plan_template__isnull=True)
    existing_plan_member_ids = set(MemberFeePlan.objects.values_list("member_id", flat=True))

    for member in members:
        member.membership_plan_template = default_template
        member.save(update_fields=["membership_plan_template", "updated_at"])

        if member.id in existing_plan_member_ids:
            continue

        MemberFeePlan.objects.create(
            member=member,
            plan_template=default_template,
            billing_cycle=default_template.duration_type,
            cycle_fee_amount=default_template.fee,
            default_cycle_discount_amount="0.00",
            currency="AFN",
            effective_from=member.join_date,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0006_backfill_member_plan_templates"),
        ("payments", "0005_memberfeeplan_plan_template_and_more"),
        ("system_settings", "0003_remove_systempreferencesettings_language"),
    ]

    operations = [
        migrations.RunPython(assign_default_plan_to_unplanned_members, noop_reverse),
    ]
