# Generated by Django 6.0.2 on 2026-06-26 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_member_schedule_class'),
        ('schedule', '0004_alter_scheduleslot_trainer'),
        ('system_settings', '0003_remove_systempreferencesettings_language'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='member',
            new_name='members_schedul_9f33e0_idx',
            old_name='members_schedule_class_id_idx',
        ),
        migrations.AddField(
            model_name='member',
            name='schedule_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_members', to='schedule.scheduleslot'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['schedule_slot'], name='members_schedul_7fb410_idx'),
        ),
    ]
