# Generated by Django 6.0.2 on 2026-08-13 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_gym_alter_user_managers_and_more'),
        ('members', '0010_member_body_metric_history'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='memberbodymetrichistory',
            new_name='member_body_member__8e513e_idx',
            old_name='member_body_member__89de2d_idx',
        ),
        migrations.RenameIndex(
            model_name='memberbodymetrichistory',
            new_name='member_body_created_bd2a59_idx',
            old_name='member_body_created_5665af_idx',
        ),
        migrations.AddField(
            model_name='member',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.gym'),
        ),
        migrations.AddField(
            model_name='memberbodymetrichistory',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.gym'),
        ),
    ]
