# Generated by Django 6.0.2 on 2026-08-13 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_backfill_existing_records_to_default_gym'),
        ('core', '0007_uploaded_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.gym'),
        ),
    ]
